### ISSUE TITLE
Problem when implementing a loop throught an object

### ISSUE THREAD

**Issue by fabregasf** [jomendez/ionic-firestore-crud-example#1]
As your code shows, inside de Promise there is a loop throght a object querySnapshot.foreach. I've tried to copy to my own project, but it doesn't work well. It shows this error in console: 
In my case, I'm retrieving passwords...
![error](https://user-images.githubusercontent.com/10199180/49297092-112eec80-f4a1-11e8-902f-230eed7739e0.png)

**Comment by jomendez** [comment]
I ran it in my local environment and it works, it looks like should be a version problem with angularfire2 and/or firebase package.
these are the versions used on the original project:
    "angularfire2": "^5.0.0-rc.6",
    "firebase": "^4.11.0",

Try to install in your new project the specific version:

npm install  angularfire2@5.0.0-rc.6 --save
npm install firebase@4.11.0 --save

Also make sure you have installed ionic 3.x (this demo was created with this version) you can run ionic info command.

Note:
I'll try to get some free time to update this project to use the latest versions of firestore and ionic
